In [5]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import numpy as np
import pdb

In [6]:
data = pd.read_csv('C:\\Users\\raibe\\Desktop\\Thesis Code\\datasets\\mortgage\\WideFormatMortgageAfterRemovingNull.csv')

In [7]:
data.head()

,id,time,duration,orig_time,first_time,mat_time,balance_time,LTV_time,interest_rate_time,hpi_time,gdp_time,uer_time,REtype_CO_orig_time,REtype_PU_orig_time,REtype_SF_orig_time,investor_orig_time,balance_orig_time,FICO_orig_time,LTV_orig_time,Interest_Rate_orig_time,hpi_orig_time,default_time,payoff_time,status_time
0,1,48,24,-7,25,113,29087.21,26.658065,9.200,146.45,2.715903,8.3,0,0,1,0,45000.0,715,69.4,9.200,87.03,1,0,1
1,2,26,2,18,25,138,105654.77,65.469851,7.680,225.10,2.151365,4.7,0,0,1,0,107200.0,558,80.0,7.680,186.91,0,1,2
2,3,29,5,-6,25,114,44378.60,31.459735,11.375,217.37,1.692969,4.5,0,0,1,0,48600.0,680,83.6,8.750,89.58,0,1,2
3,4,60,36,-2,25,119,52686.35,34.898842,10.500,189.82,2.836358,5.7,0,0,1,0,63750.0,587,81.8,10.500,97.99,0,0,0
4,5,27,3,18,25,138,52100.71,66.346343,9.155,222.39,2.361722,4.4,0,0,1,0,52800.0,527,80.0,9.155,186.91,0,1,2

In [8]:
data.shape

(49982, 24)

In [10]:
data['balance_time'] = data['balance_time'].astype(int)
data['balance_orig_time'] = data['balance_orig_time'].astype(int)

In [11]:
data.describe()

,id,time,duration,orig_time,first_time,mat_time,balance_time,LTV_time,interest_rate_time,hpi_time,gdp_time,uer_time,REtype_CO_orig_time,REtype_PU_orig_time,REtype_SF_orig_time,investor_orig_time,balance_orig_time,FICO_orig_time,LTV_orig_time,Interest_Rate_orig_time,hpi_orig_time,default_time,payoff_time,status_time
count,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,4.998200e+04,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,4.998200e+04,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000,49982.000000
mean,24994.996839,36.169181,12.473731,20.393682,24.695450,137.931755,2.390447e+05,79.312091,7.013339,190.288669,1.690157,6.001022,0.064983,0.115902,0.623625,0.118443,2.520676e+05,661.337161,79.708497,5.442932,196.394224,0.303089,0.531831,1.366752
std,14433.521449,13.992462,11.644005,7.877197,7.898944,17.936965,2.030909e+05,25.132774,2.212933,26.286991,1.917991,1.674631,0.246499,0.320110,0.484481,0.323135,2.088504e+05,72.773625,9.920236,3.286867,34.327924,0.459598,0.498991,0.749943
min,1.000000,1.000000,1.000000,-40.000000,1.000000,18.000000,0.000000e+00,0.000000,0.000000,107.830000,-4.146711,3.800000,0.000000,0.000000,0.000000,0.000000,4.791000e+03,400.000000,50.100000,0.000000,75.710000,0.000000,0.000000,0.000000
25%,12496.250000,26.000000,4.000000,17.000000,20.000000,136.000000,1.059285e+05,64.116470,5.875000,162.090000,1.229172,4.700000,0.000000,0.000000,0.000000,0.000000,1.140000e+05,612.000000,75.000000,3.000000,179.450000,0.000000,0.000000,1.000000
50%,24991.500000,32.000000,8.000000,22.000000,25.000000,141.000000,1.836600e+05,78.718905,7.000000,189.820000,2.274218,5.500000,0.000000,0.000000,1.000000,0.000000,1.920000e+05,663.000000,80.000000,6.375000,212.730000,0.000000,1.000000,2.000000
75%,37486.750000,46.000000,18.000000,25.000000,28.000000,145.000000,3.195982e+05,95.745375,8.350000,217.370000,2.836358,6.500000,0.000000,0.000000,1.000000,0.000000,3.350000e+05,715.000000,85.000000,7.625000,222.390000,1.000000,1.000000,2.000000
max,50000.000000,60.000000,60.000000,60.000000,60.000000,229.000000,8.688100e+06,616.985143,37.500000,226.290000,5.132464,10.000000,1.000000,1.000000,1.000000,1.000000,8.000000e+06,840.000000,218.500000,19.750000,226.290000,1.000000,1.000000,2.000000

In [12]:
data.shape

(49982, 24)

In [13]:
data.drop(data[data['balance_time']>1000000].index, inplace = True)
data.drop(data[data['balance_orig_time']>1000000].index, inplace = True)

In [14]:
data = data.drop(['id', 'time', 'first_time', 'default_time', 'status_time'], axis=True)
df = data[['orig_time', 'mat_time',	'balance_time',	'LTV_time',	'interest_rate_time', 'hpi_time',	'gdp_time',	'uer_time',	'REtype_CO_orig_time',	
           'REtype_PU_orig_time',	'REtype_SF_orig_time',	'investor_orig_time',	'balance_orig_time', 	'FICO_orig_time', 	'LTV_orig_time',	
           'Interest_Rate_orig_time', 	'hpi_orig_time', 'duration', 'payoff_time']]

In [15]:
df.head()

,orig_time,mat_time,balance_time,LTV_time,interest_rate_time,hpi_time,gdp_time,uer_time,REtype_CO_orig_time,REtype_PU_orig_time,REtype_SF_orig_time,investor_orig_time,balance_orig_time,FICO_orig_time,LTV_orig_time,Interest_Rate_orig_time,hpi_orig_time,duration,payoff_time
0,-7,113,29087,26.658065,9.200,146.45,2.715903,8.3,0,0,1,0,45000,715,69.4,9.200,87.03,24,0
1,18,138,105654,65.469851,7.680,225.10,2.151365,4.7,0,0,1,0,107200,558,80.0,7.680,186.91,2,1
2,-6,114,44378,31.459735,11.375,217.37,1.692969,4.5,0,0,1,0,48600,680,83.6,8.750,89.58,5,1
3,-2,119,52686,34.898842,10.500,189.82,2.836358,5.7,0,0,1,0,63750,587,81.8,10.500,97.99,36,0
4,18,138,52100,66.346343,9.155,222.39,2.361722,4.4,0,0,1,0,52800,527,80.0,9.155,186.91,3,1

In [16]:
df.shape

(49629, 19)

In [17]:
import random
random.seed(1234)
df_test = df.sample(frac=0.2)
df_train = df.drop(df_test.index)

In [18]:
df_test.shape

(9926, 19)

In [19]:
df_train.shape

(39703, 19)

In [20]:
df_train.to_csv('C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\trainDRAS.txt', index=False, header=False)
df_test.to_csv('C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\testDRAS.txt', index=False, header=False)

In [ ]:
orig_time result:
max value:60.0    min value:-40.0   distinct cnt:98
mat_time result:
max value:229.0    min value:18.0   distinct cnt:199
balance_time result:
max value:1000000.0    min value:0.0   distinct cnt:43482
LTV_time result:
max value:616.98514262    min value:0.0   distinct cnt:45989
interest_rate_time result:
max value:37.5    min value:0.0   distinct cnt:2720
hpi_time result:
max value:226.29    min value:107.83   distinct cnt:60
gdp_time result:
max value:5.1324641859    min value:-4.146710947   distinct cnt:60
uer_time result:
max value:10.0    min value:3.8   distinct cnt:36
REtype_CO_orig_time result:
max value:1.0    min value:0.0   distinct cnt:2
REtype_PU_orig_time result:
max value:1.0    min value:0.0   distinct cnt:2
REtype_SF_orig_time result:
max value:1.0    min value:0.0   distinct cnt:2
investor_orig_time result:
max value:1.0    min value:0.0   distinct cnt:2
balance_orig_time result:
max value:1000000.0    min value:4791.0   distinct cnt:10475
FICO_orig_time result:
max value:840.0    min value:400.0   distinct cnt:397
LTV_orig_time result:
max value:218.5    min value:50.1   distinct cnt:552
Interest_Rate_orig_time result:
max value:19.75    min value:0.0   distinct cnt:1699
hpi_orig_time result:
max value:226.29    min value:75.71   distinct cnt:97

In [24]:
import argparse
import random
import pdb

features = ["orig_time", "mat_time", "balance_time", "LTV_time", "interest_rate_time", "hpi_time", "gdp_time", "uer_time", "REtype_CO_orig_time",
            "REtype_PU_orig_time", "REtype_SF_orig_time", "investor_orig_time", "balance_orig_time", "FICO_orig_time", "LTV_orig_time",
            "Interest_Rate_orig_time", "hpi_orig_time"]

# feat_dict: featname: set()---distinct feat values
feat_dict = {}

# (max_value +1) +1
feat_size = { 
    "orig_time": [-40,61 + 1],
    "mat_time": [18,229 +1],
    "balance_time": [0, 1000001 + 1],
    "LTV_time": [0 , 45990+1], # 616.98514262 * 74.53 (distinct 45989) # 616.98514262 is the max value of the feature, we multiply it with the number to get as much distinct values as there is, in this case 45989
    "interest_rate_time": [0, 2721+ 1] , # 37.5 * 72.53 (distinct 2720) # 37.5 is the max value of the feature 
    "hpi_time": [107, 227 + 1],
    "gdp_time": [-28, 35 + 1], # 5.1324641859 * 6.66 (distinct 60) {the distance from -4 tp 5 is almost 9, dividing 9 on 60, we get almost 6.7}
    # lower limit -4.146710947 * 6.66 almost -28, higher limit 5.1324641859 * 6.66 is amost 35
    "uer_time": [0, 37 + 1], # 10 * 3.6 (distinct 36)
    "REtype_CO_orig_time": [0, 2 + 1],
    "REtype_PU_orig_time": [0, 2 + 1],
    "REtype_SF_orig_time": [0, 2 + 1],
    "investor_orig_time": [0, 2 + 1],
    "balance_orig_time": [4791, 1000001 + 1],
    "FICO_orig_time": [400, 841 + 1],
    "LTV_orig_time": [0, 553 + 1], # 218.5 * 2.523 (distinct 552)
    "Interest_Rate_orig_time": [0, 1700 +1], # 19.75 * 86 (distinct 1699)
    "hpi_orig_time": [75, 228 + 1]  
}

# feat_index
feat_index = {}

# build feat_index
def build_feat_index(feat_index_f):
    max_index = 0
    feat_index_lines = []
    #pdb.set_trace()
    # truncate
    feat_index["0:truncate"] = max_index
    feat_index_lines.append("0:truncate\t{}\n".format(max_index))
    max_index += 1

    for i in range(len(features)):
        feat_num = i + 1
        # other
        feat_index["{}:other".format(feat_num)] = max_index
        feat_index_lines.append("{}:other\t{}\n".format(feat_num, max_index))
        max_index += 1
        # normal values
        low = feat_size[features[i]][0]
        high = feat_size[features[i]][1]
        for value in range(low, high):
            feat_index["{}:{}".format(feat_num, value)] = max_index
            feat_index_lines.append("{}:{}\t{}\n".format(feat_num, value, max_index))
            max_index += 1

    # write feat_index file:
    with open(feat_index_f, 'w') as f:
        f.writelines(feat_index_lines)

    return feat_index, feat_index_lines
 
def get_feat_val(feat_name, str_val):
  if feat_name == "LTV_time":
      return int(float(str_val) * 74.53)
  elif feat_name == "interest_rate_time":
      return int(float(str_val) * 72.53)
  elif feat_name == "gdp_time":
      return int(float(str_val) * 6.66)
  elif feat_name == "uer_time":
      return int(float(str_val) * 3.6)
  elif feat_name == "LTV_orig_time":
      return int(float(str_val) * 2.523)
  elif feat_name == "Interest_Rate_orig_time":
      return int(float(str_val) * 86)    
  else:
      return  int(float(str_val))

# build yzbx data
# y is always 0 
# z is the true time if e=1 and the randomly predicted time (bigger than the ture time) if e=0
# b is the true time if e=0, and the randomly predicted time (bigger than the ture time) if e=1
# x is the encoded features 
def build_yzbx_data(ft_ind,raw_train, raw_test, yzbx_train, yzbx_test):
    fnames_i = [raw_train, raw_test] # it will only inculde the db names as strings 
    fnames_o = [yzbx_train, yzbx_test] # the destination directories of the resulted files as strings 
    #pdb.set_trace()
    for j in range(len(fnames_i)): # len(fnames_i) wiill be 2
        yzbx_list = []
        with open(fnames_i[j], 'r') as f: # openning the first file, which the train file in the first loop 
            lines = f.readlines() # reading all the lines
            for line in lines:# getting each line after the other 
                # the first line would be '-7,113,29087,26.658065492,9.2,146.45,2.7159028845999997,8.3,0,0,1,0,45000,715,69.4,9.2,87.03,24,1\n'
                x_items = []
                # truncate
                x_items.append("0:1") # append the first value to x_itmes
                line_items = line.split(',') # split the line to items saperated by comma
                # line_items will contain: ['-7', '113', '29087', '26.658065492', '9.2', '146.45', '2.7159028845999997', '8.3', '0', '0', '1', '0', '45000', '715', '69.4', '9.2', '87.03', '24', '1\n']
                for i in range(len(line_items) - 2): # again -2 to exclude the time and lable, because lable and time are in the last position in the dataset
                    # in this for we go through each item in line_items individually 
                    feat_num = i + 1
                    feat_name = features[i] # the first feature is "orig_time"
                    feat_val = get_feat_val(feat_name, line_items[i]) # return integer value, line_items[0] = '-7' "orig_time"
                                                                      # if the feature is LTV_time, then we multiply the true value 26.658065492
                                                                      # with 74.53 yielding feat_val = 1986
                    #"orig_time" feat_val = -7
                    key = "{}:{}".format(feat_num, feat_val) #contain feature number and the real value of the feature 
                    #key = {'1:-7'}
                    if key not in ft_ind.keys(): # if the key deosn't exsit in the feature index file
                        key = "{}:other".format(feat_num)    
                    x_items.append("{}:1".format(ft_ind[key])) # append '35:1" to x_items, where 35 the value assigned to the key {'1:-7'} and 1 is the feature position
                                                               # '1002307:1'LTV_time
                # get b and z
                # t from hour to day
                t = int(float(line_items[-2])) # get the time which is the column before the last, hence -2, 
                                                         #time is 30 here, divide by 24 equal 1.25, convert to int then t is 1, add 1 then the result is 2
                e = int(float(line_items[-1]))
                if e == 1:# if event happens, then we know z the true time and we take a rendom number for 
                    z = t # 24
                    b = random.randint(z + 1, 2 * (z + 1)) # A random integer in range [start, end] including the end points. 
                                                            # randint(24 + 1, 2 * (24 + 1)) = randint(25, 50) = 39
                else: # if cens
                    b = t
                    z = random.randint(b + 1, 2 * (b + 1))
                # dummy y
                y = 0
                yzbx = ' '.join([str(y), str(z), str(b)] + x_items)
                yzbx_list.append(yzbx + '\n')

        with open(fnames_o[j], 'w') as f:
            f.writelines(yzbx_list)

      


# calculate features' statistical: max value, min value, mean value, and different value counts
def feat_stat(train, test):
    for feat in features:
        feat_dict[feat] = set() # we set a dictionary with the features names to add values to it in the for loops below
    #pdb.set_trace()
    # train
    with open(train, 'r') as f:
        lines = f.readlines()
        for line in lines:
            items = line.split(',')
            for i in range(len(items) - 2): # here -2 because we don't want to include the time and the label, which are located in the last two indexes
                feat_name = features[i]
                feat_dict[feat_name].add(float(items[i]))
    # test
    with open(test, 'r') as f:
        lines = f.readlines()
        for line in lines:
            items = line.split(',')
            for i in range(len(items) - 2):
                feat_name = features[i]
                feat_dict[feat_name].add(float(items[i]))
    
    # print result
    for feat in features:
        stats = feat_dict[feat]
        print("{} result:".format(feat))
        print("max value:{0}    min value:{1}   distinct cnt:{2}".format(max(stats), min(stats), len(stats)))


#def main(args):
    # calculate statistical results on dataset
    #feat_stat(train.csv, test.csv)
    # build_feat_index(args.featindex)
    # build_yzbx_data(args.raw_train, args.raw_test, args.yzbx_train, args.yzbx_test)



'''
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="feature engineering for SUPPORT clinical dataset")
    parser.add_argument(
        "--raw_train", action="store", required=True, help="raw train file name")
    parser.add_argument(
        "--raw_test", action="store", required=True, help="raw test file name")
    parser.add_argument(
        "--yzbx_train", action="store", required=True, help="train yzbx")
    parser.add_argument(
        "--yzbx_test", action="store", required=True, help="test yzbx")    
    parser.add_argument(
        "--featindex", action="store", required=True, help="feature index")
    args = parser.parse_args()
    main(args) '''

'\nif __name__ == "__main__":\n    parser = argparse.ArgumentParser(\n        description="feature engineering for SUPPORT clinical dataset")\n    parser.add_argument(\n        "--raw_train", action="store", required=True, help="raw train file name")\n    parser.add_argument(\n        "--raw_test", action="store", required=True, help="raw test file name")\n    parser.add_argument(\n        "--yzbx_train", action="store", required=True, help="train yzbx")\n    parser.add_argument(\n        "--yzbx_test", action="store", required=True, help="test yzbx")    \n    parser.add_argument(\n        "--featindex", action="store", required=True, help="feature index")\n    args = parser.parse_args()\n    main(args) '

In [25]:
a,b = build_feat_index('C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\feat_ind.txt')

In [26]:
build_yzbx_data(a,"C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\trainDRAS.txt", "C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\testDRAS.txt", "C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\train_yzb.txt", "C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\Mortgage_p\\test_yzb.txt")