In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import numpy as np
import pdb

In [3]:
data = pd.read_csv('C:\\Users\\raibe\\Desktop\\Thesis Code\\datasets\\\data batches\\ndb1.csv', sep=',')

In [3]:
data.head()

,time,label,current_year,default,payoff,int.rate,orig.upb,fico.score,dti.r,ltv.r,bal.repaid,t.act.12m,t.del.30d.12m,t.del.60d.12m,hpi.st.d.t.o,hpi.zip.o,hpi.zip.d.t.o,ppi.c.FRMA,TB10Y.d.t.o,FRMA30Y.d.t.o,ppi.o.FRMA,equity.est,hpi.st.log12m,hpi.r.st.us,hpi.r.zip.st,st.unemp.r12m,st.unemp.r3m,TB10Y.r12m,T10Y3MM,T10Y3MM.r12m
0,28,1,2005,0,1,6.125,158000,741,43,88,2.858481,12,0,0,10.017040,140.00,16.14,0.355,0.22,-0.02,0.335,46760.880,0.042702,0.750867,1.309409,-0.5,-0.2,-0.32,0.96,-2.21
1,12,1,2003,0,1,6.875,77000,752,23,76,0.655052,12,0,0,7.036967,136.21,3.16,1.085,-1.20,-0.97,0.115,27170.650,0.072084,0.997273,1.151251,0.5,0.0,-1.25,2.83,-0.67
2,12,1,2003,0,1,6.375,219000,651,50,95,1.057890,12,0,0,18.246120,170.02,19.80,0.395,0.33,-0.33,0.065,40503.680,0.144051,1.140516,1.308080,0.1,-0.1,0.40,3.33,1.09
3,17,1,2006,0,1,5.750,120000,724,28,55,2.388167,12,0,0,52.602680,203.89,70.56,-0.830,0.76,0.77,-0.060,176553.600,0.174647,1.356698,1.222113,-0.7,0.0,0.65,0.39,-1.17
4,8,1,2001,0,1,7.625,128000,797,43,97,4.328320,12,0,0,4.002571,125.93,2.75,0.605,-0.49,-0.10,0.505,9672.395,0.062330,0.992343,1.211832,0.2,0.2,-1.07,2.78,3.23

In [4]:
data.describe()

,time,label,current_year,default,payoff,int.rate,orig.upb,fico.score,dti.r,ltv.r,bal.repaid,t.act.12m,t.del.30d.12m,t.del.60d.12m,hpi.st.d.t.o,hpi.zip.o,hpi.zip.d.t.o,ppi.c.FRMA,TB10Y.d.t.o,FRMA30Y.d.t.o,ppi.o.FRMA,equity.est,hpi.st.log12m,hpi.r.st.us,hpi.r.zip.st,st.unemp.r12m,st.unemp.r3m,TB10Y.r12m,T10Y3MM,T10Y3MM.r12m
count,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,21.831000,1.006800,2003.020800,0.02960,0.947600,7.156139,147116.600000,712.734200,33.961900,75.794600,3.017991,11.723600,0.2125,0.063900,16.660184,144.693859,21.206993,0.949907,-0.729491,-0.789842,0.160065,9.065689e+04,0.081423,0.986797,1.326740,0.266150,0.072610,-0.456149,2.166420,0.064762
std,14.926008,0.228821,1.586575,0.16949,0.222843,0.899476,67044.957358,56.537473,11.105385,15.231855,7.471110,1.227173,0.9305,0.430157,18.399218,27.646143,24.485466,0.809058,0.808197,0.775021,0.500020,9.645067e+04,0.054870,0.127164,0.167931,0.795596,0.351848,0.724259,1.114589,1.475540
min,1.000000,0.000000,1999.000000,0.00000,0.000000,4.750000,17000.000000,300.000000,1.000000,9.000000,-0.879790,0.000000,0.0000,0.000000,-9.437743,86.730000,-4.900000,-1.655000,-3.330000,-3.380000,-2.120000,0.000000e+00,-0.051914,0.654297,0.714778,-7.000000,-6.300000,-1.600000,-0.530000,-2.430000
25%,11.000000,1.000000,2002.000000,0.00000,1.000000,6.500000,96000.000000,674.000000,26.000000,70.000000,0.947280,12.000000,0.0000,0.000000,5.056461,126.817500,6.690000,0.465000,-1.270000,-1.270000,-0.180000,3.586829e+04,0.037815,0.911426,1.230751,-0.300000,-0.100000,-1.060000,1.560000,-0.930000
50%,18.000000,1.000000,2003.000000,0.00000,1.000000,7.125000,137000.000000,720.000000,34.000000,80.000000,1.702829,12.000000,0.0000,0.000000,10.595450,137.840000,13.060000,0.975000,-0.760000,-0.840000,0.145000,6.252688e+04,0.068338,0.983147,1.314443,0.200000,0.000000,-0.600000,2.500000,-0.220000
75%,28.000000,1.000000,2004.000000,0.00000,1.000000,7.875000,190000.000000,758.000000,42.000000,85.000000,2.923637,12.000000,0.0000,0.000000,21.293543,154.890000,25.922500,1.460000,-0.090000,-0.210000,0.485000,1.094974e+05,0.115062,1.049634,1.429746,0.700000,0.200000,0.090000,2.890000,1.030000
max,72.000000,2.000000,2006.000000,1.00000,1.000000,10.750000,500000.000000,831.000000,65.000000,100.000000,99.969920,12.000000,12.0000,10.000000,137.253600,340.810000,216.080000,4.570000,1.780000,1.480000,3.370000,2.084969e+06,0.325950,1.439223,2.085582,5.400000,5.800000,1.940000,3.700000,3.930000

In [5]:
data.columns

Index(['time', 'label', 'current_year', 'default', 'payoff', 'int.rate',
       'orig.upb', 'fico.score', 'dti.r', 'ltv.r', 'bal.repaid', 't.act.12m',
       't.del.30d.12m', 't.del.60d.12m', 'hpi.st.d.t.o', 'hpi.zip.o',
       'hpi.zip.d.t.o', 'ppi.c.FRMA', 'TB10Y.d.t.o', 'FRMA30Y.d.t.o',
       'ppi.o.FRMA', 'equity.est', 'hpi.st.log12m', 'hpi.r.st.us',
       'hpi.r.zip.st', 'st.unemp.r12m', 'st.unemp.r3m', 'TB10Y.r12m',
       'T10Y3MM', 'T10Y3MM.r12m'],
      dtype='object')

In [4]:
data = data.drop(['label', 'current_year', 'default'], axis=True)
df = data[['int.rate', 'orig.upb', 'fico.score', 'dti.r', 'ltv.r', 'bal.repaid', 't.act.12m',
       't.del.30d.12m', 't.del.60d.12m', 'hpi.st.d.t.o', 'hpi.zip.o',
       'hpi.zip.d.t.o', 'ppi.c.FRMA', 'TB10Y.d.t.o', 'FRMA30Y.d.t.o',
       'ppi.o.FRMA', 'equity.est', 'hpi.st.log12m', 'hpi.r.st.us',
       'hpi.r.zip.st', 'st.unemp.r12m', 'st.unemp.r3m', 'TB10Y.r12m',
       'T10Y3MM', 'T10Y3MM.r12m', 'time', 'payoff']]

In [5]:
df.head()

,int.rate,orig.upb,fico.score,dti.r,ltv.r,bal.repaid,t.act.12m,t.del.30d.12m,t.del.60d.12m,hpi.st.d.t.o,hpi.zip.o,hpi.zip.d.t.o,ppi.c.FRMA,TB10Y.d.t.o,FRMA30Y.d.t.o,ppi.o.FRMA,equity.est,hpi.st.log12m,hpi.r.st.us,hpi.r.zip.st,st.unemp.r12m,st.unemp.r3m,TB10Y.r12m,T10Y3MM,T10Y3MM.r12m,time,payoff
0,7.00,63000,657,26,79,2.078556,11,1,0,28.160240,156.72,27.98,0.99,0.48,0.02,1.01,32293.92,0.146144,1.110008,1.234804,-0.7,-0.1,0.39,3.41,0.58,20,1
1,7.00,132000,647,33,80,0.583939,11,1,0,11.665370,194.94,14.71,1.01,-1.41,-1.19,-0.18,46221.55,0.146154,1.078726,1.668582,0.9,0.1,-0.86,2.24,0.15,7,1
2,6.25,152000,761,29,80,0.871974,12,0,0,9.965809,132.33,1.89,-0.07,0.42,0.39,0.32,42039.07,0.093969,1.054944,1.006483,0.6,0.0,0.19,3.50,0.86,9,1
3,7.00,50000,758,24,37,3.386060,12,0,0,12.049330,127.51,18.29,-0.02,-0.89,-0.21,-0.23,106211.90,0.033797,0.968266,1.407201,2.1,0.9,-1.07,2.78,3.23,31,1
4,6.75,181000,653,29,55,1.415833,11,1,0,5.245197,161.82,6.88,0.81,-0.93,-0.87,-0.06,163735.70,0.017066,0.893576,1.507073,0.5,0.0,-0.67,3.08,0.11,18,1

In [8]:
df.shape

(10000, 27)

In [6]:
import random
random.seed(1234)
df_test = df.sample(frac=0.2)
df_train = df.drop(df_test.index)
print("test:{}, train:{}, all: {}".format(len(df_test), len(df_train),
                                                    len(df_test) +  len(df_train)))

test:2000, train:8000, all: 10000

In [94]:
#import random
#random.seed(1234)
#df_test = df.sample(frac=0.2)
#df_train1 = df.drop(df_test.index)
#df_valid = df_train1.sample(frac=0.2)
#df_train = df_train1.drop(df_valid.index)
#print("test:{}, valid:{}, train:{}, all: {}".format(len(df_test), len(df_valid), len(df_train),
#                                                    len(df_test) + len(df_valid) + len(df_train)))

test:2000, valid:1600, train:6400, all: 10000

In [8]:
df_train.head()

,int.rate,orig.upb,fico.score,dti.r,ltv.r,bal.repaid,t.act.12m,t.del.30d.12m,t.del.60d.12m,hpi.st.d.t.o,hpi.zip.o,hpi.zip.d.t.o,ppi.c.FRMA,TB10Y.d.t.o,FRMA30Y.d.t.o,ppi.o.FRMA,equity.est,hpi.st.log12m,hpi.r.st.us,hpi.r.zip.st,st.unemp.r12m,st.unemp.r3m,TB10Y.r12m,T10Y3MM,T10Y3MM.r12m,time,payoff
0,7.00,63000,657,26,79,2.078556,11,1,0,28.160240,156.72,27.98,0.99,0.48,0.02,1.01,32293.92,0.146144,1.110008,1.234804,-0.7,-0.1,0.39,3.41,0.58,20,1
1,7.00,132000,647,33,80,0.583939,11,1,0,11.665370,194.94,14.71,1.01,-1.41,-1.19,-0.18,46221.55,0.146154,1.078726,1.668582,0.9,0.1,-0.86,2.24,0.15,7,1
2,6.25,152000,761,29,80,0.871974,12,0,0,9.965809,132.33,1.89,-0.07,0.42,0.39,0.32,42039.07,0.093969,1.054944,1.006483,0.6,0.0,0.19,3.50,0.86,9,1
3,7.00,50000,758,24,37,3.386060,12,0,0,12.049330,127.51,18.29,-0.02,-0.89,-0.21,-0.23,106211.90,0.033797,0.968266,1.407201,2.1,0.9,-1.07,2.78,3.23,31,1
4,6.75,181000,653,29,55,1.415833,11,1,0,5.245197,161.82,6.88,0.81,-0.93,-0.87,-0.06,163735.70,0.017066,0.893576,1.507073,0.5,0.0,-0.67,3.08,0.11,18,1

In [118]:
df_train.shape

(8000, 27)

In [7]:
print(df_train['payoff'] [df_train['payoff'] == 1].count())
print(df_test['payoff'] [df_test['payoff'] == 1].count())

7577
1891

In [9]:
train_file = 'C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\ndb_p\\1\\trainDRSA.txt'
test_file ='C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\ndb_p\\1\\testDRSA.txt'
#valid_file ='C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\ndb_p\\1\\validDRSA.txt'

In [10]:
df_train.to_csv(train_file, index=False, header=False)
df_test.to_csv(test_file, index=False, header=False)
#df_valid.to_csv(valid_file, index=False, header=False)

In [124]:
feat_stat(train_file, test_file)

int.rate result:
max value:10.875    min value:4.75   distinct cnt:89
orig.upb result:
max value:599000.0    min value:14000.0   distinct cnt:345
fico.score result:
max value:826.0    min value:300.0   distinct cnt:287
dti.r result:
max value:65.0    min value:1.0   distinct cnt:65
ltv.r result:
max value:100.0    min value:6.0   distinct cnt:87
bal.repaid result:
max value:99.97442    min value:-1.067826   distinct cnt:9082
t.act.12m result:
max value:12.0    min value:0.0   distinct cnt:13
t.del.30d.12m result:
max value:12.0    min value:0.0   distinct cnt:13
t.del.60d.12m result:
max value:9.0    min value:0.0   distinct cnt:9
hpi.st.d.t.o result:
max value:141.666    min value:-10.60582   distinct cnt:8899
hpi.zip.o result:
max value:357.27    min value:86.78   distinct cnt:4066
hpi.zip.d.t.o result:
max value:213.81    min value:-8.95   distinct cnt:4249
ppi.c.FRMA result:
max value:4.635    min value:-1.845   distinct cnt:798
TB10Y.d.t.o result:
max value:1.78    min value:-3.33   distinct cnt:405
FRMA30Y.d.t.o result:
max value:1.69    min value:-3.38   distinct cnt:416
ppi.o.FRMA result:
max value:3.38    min value:-1.81   distinct cnt:559
equity.est result:
max value:1912545.0    min value:185.5257   distinct cnt:9987
hpi.st.log12m result:
max value:0.3259499    min value:-0.051914   distinct cnt:2664
hpi.r.st.us result:
max value:1.413932    min value:0.654297   distinct cnt:2638
hpi.r.zip.st result:
max value:2.122123    min value:0.7577754   distinct cnt:7872
st.unemp.r12m result:
max value:5.4    min value:-6.9   distinct cnt:50
st.unemp.r3m result:
max value:5.8    min value:-6.3   distinct cnt:26
TB10Y.r12m result:
max value:1.94    min value:-1.6   distinct cnt:74
T10Y3MM result:
max value:3.7    min value:-0.53   distinct cnt:83
T10Y3MM.r12m result:
max value:3.93    min value:-2.43   distinct cnt:84

In [54]:
def limits(fet, upperlimit, lowerlimit, distinct):
    l1 = round(distinct / (upperlimit - lowerlimit), 3)
    final_upper = round(l1 * upperlimit) + 1
    final_lower = round(l1 * lowerlimit)
    print("{0}[{1}, {2} + 1]  multi_factor:{3}".format(fet, final_lower, final_upper, l1))

In [53]:
int(10.875 * 14.531)

158

In [55]:
limits("int.rate",10.875, 4.75, 89)
limits("bal.repaid",99.97442, -1.067826, 9082)
limits("hpi.st.d.t.o",141.666, -10.60582, 8899)
limits("hpi.zip.o",357.27, 86.78, 4066)
limits("hpi.zip.d.t.o",213.81, -8.95, 4249)
limits("ppi.c.FRMA",4.635, -1.845, 798)
limits("TB10Y.d.t.o",1.78, -3.33, 405)
limits("FRMA30Y.d.t.o",1.69, -3.38, 416)
limits("ppi.o.FRMA",3.38, -1.81, 559)
limits("hpi.st.log12m",0.3259499, -0.051914, 2664)
limits("hpi.r.st.us",1.413932, 0.654297, 2638)
limits("hpi.r.zip.st",2.122123, 0.7577754, 7872)
limits("st.unemp.r12m",5.4, -6.9, 50)
limits("st.unemp.r3m",5.8, -6.3, 26)
limits("TB10Y.r12m",1.94, -1.6, 74)
limits("T10Y3MM result",3.7, -0.53, 83)
limits("T10Y3MM.r12m",3.93, -2.43, 84)

int.rate[69, 159 + 1]  multi_factor:14.531
bal.repaid[-96, 8987 + 1]  multi_factor:89.883
hpi.st.d.t.o[-620, 8280 + 1]  multi_factor:58.442
hpi.zip.o[1304, 5371 + 1]  multi_factor:15.032
hpi.zip.d.t.o[-171, 4079 + 1]  multi_factor:19.074
ppi.c.FRMA[-227, 572 + 1]  multi_factor:123.148
TB10Y.d.t.o[-264, 142 + 1]  multi_factor:79.256
FRMA30Y.d.t.o[-277, 140 + 1]  multi_factor:82.051
ppi.o.FRMA[-195, 365 + 1]  multi_factor:107.707
hpi.st.log12m[-366, 2299 + 1]  multi_factor:7050.157
hpi.r.st.us[2272, 4911 + 1]  multi_factor:3472.72
hpi.r.zip.st[4372, 12245 + 1]  multi_factor:5769.791
st.unemp.r12m[-28, 23 + 1]  multi_factor:4.065
st.unemp.r3m[-14, 13 + 1]  multi_factor:2.149
TB10Y.r12m[-33, 42 + 1]  multi_factor:20.904
T10Y3MM result[-10, 74 + 1]  multi_factor:19.622
T10Y3MM.r12m[-32, 53 + 1]  multi_factor:13.208

In [ ]:
3.41 * 19.622

In [11]:
import argparse
import random
import pdb

features = ['int.rate', 'orig.upb', 'fico.score', 'dti.r', 'ltv.r', 'bal.repaid', 't.act.12m',
       't.del.30d.12m', 't.del.60d.12m', 'hpi.st.d.t.o', 'hpi.zip.o',
       'hpi.zip.d.t.o', 'ppi.c.FRMA', 'TB10Y.d.t.o', 'FRMA30Y.d.t.o',
       'ppi.o.FRMA', 'equity.est', 'hpi.st.log12m', 'hpi.r.st.us',
       'hpi.r.zip.st', 'st.unemp.r12m', 'st.unemp.r3m', 'TB10Y.r12m',
       'T10Y3MM', 'T10Y3MM.r12m']

# feat_dict: featname: set()---distinct feat values
feat_dict = {}


# (max_value +1) +1
feat_size = { 
    # int.rate: 10.875 * 14.71 (distinct 89) {the distance from 4 tp 10 is almost 6, dividing 89 on 6, we get almost 14.71}
    # lower limit 4.75 * 14.71 almost 70, higher limit 10.875 * 14.71 is amost 160
    "int.rate": [69, 159 + 1], # multi_factor:14.531
    
    "orig.upb": [14000, 599001 +1],
    "fico.score": [300, 827 + 1],
    "dti.r": [1, 66 + 1],
    "ltv.r": [6, 101 + 1], 
    
    "bal.repaid": [-96, 8987 + 1],# [-96, 8986 + 1]  multi_factor:89.883
    
    "t.act.12m": [0, 13 + 1],
    "t.del.30d.12m": [0, 13 + 1],
    "t.del.60d.12m": [0, 10+ 1],
    
    "hpi.st.d.t.o":[-620, 8280 + 1],  #multi_factor:58.442
    "hpi.zip.o":[1304, 5371 + 1],  #multi_factor:15.032
    "hpi.zip.d.t.o":[-171, 4079 + 1],  #multi_factor:19.074
    "ppi.c.FRMA":[-227, 572 + 1],  #multi_factor:123.148
    "TB10Y.d.t.o":[-264, 142 + 1],  #multi_factor:79.256
    "FRMA30Y.d.t.o":[-277, 140 + 1],  #multi_factor:82.051
    "ppi.o.FRMA":[-195, 365 + 1],  #multi_factor:107.707
    
    "equity.est":[185, 1912546 + 1],
    
    "hpi.st.log12m":[-366, 2299 + 1],  #multi_factor:7050.157
    "hpi.r.st.us":[2272, 4911 + 1],  #multi_factor:3472.72
    "hpi.r.zip.st":[4372, 12245 + 1],  #multi_factor:5769.791
    "st.unemp.r12m":[-28, 23 + 1],  #multi_factor:4.065
    "st.unemp.r3m":[-14, 13 + 1],  #multi_factor:2.149
    "TB10Y.r12m":[-33, 42 + 1],  #multi_factor:20.904
    "T10Y3MM":[-10, 74 + 1],  #multi_factor:19.622
    "T10Y3MM.r12m":[-32, 53 + 1]  #multi_factor:13.208 
}

# feat_index
feat_index = {}

# build feat_index
def build_feat_index(feat_index_f):
    max_index = 0
    feat_index_lines = []
    #pdb.set_trace()
    # truncate
    feat_index["0:truncate"] = max_index
    feat_index_lines.append("0:truncate\t{}\n".format(max_index))
    max_index += 1

    for i in range(len(features)):
        feat_num = i + 1
        # other
        feat_index["{}:other".format(feat_num)] = max_index
        feat_index_lines.append("{}:other\t{}\n".format(feat_num, max_index))
        max_index += 1
        # normal values
        low = feat_size[features[i]][0]
        high = feat_size[features[i]][1]
        for value in range(low, high):
            feat_index["{}:{}".format(feat_num, value)] = max_index
            feat_index_lines.append("{}:{}\t{}\n".format(feat_num, value, max_index))
            max_index += 1

    # write feat_index file:
    with open(feat_index_f, 'w') as f:
        f.writelines(feat_index_lines)

    return feat_index, feat_index_lines
 
def get_feat_val(feat_name, str_val):
    if feat_name == "int.rate":
        return int(float(str_val) * 14.531)
    elif feat_name == "bal.repaid":
        return int(float(str_val) * 89.883)
    elif feat_name == "hpi.st.d.t.o":
        return int(float(str_val) * 58.442)
    elif feat_name == "hpi.zip.o":
        return int(float(str_val) * 15.032)
    elif feat_name == "hpi.zip.d.t.o":
        return int(float(str_val) * 19.074)
    elif feat_name == "ppi.c.FRMA":
        return int(float(str_val) * 123.148) 
    if feat_name == "TB10Y.d.t.o":
        return int(float(str_val) * 79.256)
    elif feat_name == "FRMA30Y.d.t.o":
        return int(float(str_val) * 82.051)
    elif feat_name == "ppi.o.FRMA":
        return int(float(str_val) * 107.707)
    elif feat_name == "hpi.st.log12m":
        return int(float(str_val) * 7050.157)
    elif feat_name == "hpi.r.st.us":
        return int(float(str_val) * 3472.72)
    elif feat_name == "hpi.r.zip.st":
        return int(float(str_val) * 5769.791) 
    if feat_name == "st.unemp.r12m":
        return int(float(str_val) * 4.065)
    elif feat_name == "st.unemp.r3m":
        return int(float(str_val) * 2.149)
    elif feat_name == "TB10Y.r12m":
        return int(float(str_val) * 20.904)
    elif feat_name == "T10Y3MM":
        return int(float(str_val) * 19.622)
    elif feat_name == "T10Y3MM.r12m":
        return int(float(str_val) * 13.208)
    else:
        return  int(float(str_val))

# build yzbx data
# y is always 0 
# z is the true time if e=1 and the randomly predicted time (bigger than the ture time) if e=0
# b is the true time if e=0, and the randomly predicted time (bigger than the ture time) if e=1
# x is the encoded features 
def build_yzbx_data(ft_ind,raw_train, raw_test, yzbx_train, yzbx_test):
    fnames_i = [raw_train, raw_test] # it will only inculde the db names as strings 
    fnames_o = [yzbx_train, yzbx_test] # the destination directories of the resulted files as strings 
    #pdb.set_trace()
    for j in range(len(fnames_i)): # len(fnames_i) wiill be 2
        yzbx_list = []
        with open(fnames_i[j], 'r') as f: # openning the first file, which the train file in the first loop 
            lines = f.readlines() # reading all the lines
            for line in lines:# getting each line after the other 
                # the first line would be '-7,113,29087,26.658065492,9.2,146.45,2.7159028845999997,8.3,0,0,1,0,45000,715,69.4,9.2,87.03,24,1\n'
                x_items = []
                # truncate
                x_items.append("0:1") # append the first value to x_itmes
                line_items = line.split(',') # split the line to items saperated by comma
                # line_items will contain: ['-7', '113', '29087', '26.658065492', '9.2', '146.45', '2.7159028845999997', '8.3', '0', '0', '1', '0', '45000', '715', '69.4', '9.2', '87.03', '24', '1\n']
                for i in range(len(line_items) - 2): # again -2 to exclude the time and lable, because lable and time are in the last position in the dataset
                    # in this for we go through each item in line_items individually 
                    feat_num = i + 1
                    feat_name = features[i] # the first feature is "orig_time"
                    feat_val = get_feat_val(feat_name, line_items[i]) # return integer value, line_items[0] = '-7' "orig_time"
                                                                      # if the feature is LTV_time, then we multiply the true value 26.658065492
                                                                      # with 74.53 yielding feat_val = 1986
                    #"orig_time" feat_val = -7
                    key = "{}:{}".format(feat_num, feat_val) #contain feature number and the real value of the feature 
                    #key = {'1:-7'}
                    if key not in ft_ind.keys(): # if the key deosn't exsit in the feature index file
                        key = "{}:other".format(feat_num)    
                    x_items.append("{}:1".format(ft_ind[key])) # append '35:1" to x_items, where 35 the value assigned to the key {'1:-7'} and 1 is the feature position
                                                               # '1002307:1'LTV_time
                # get b and z
                # t from hour to day
                t = int(float(line_items[-2])) # get the time which is the column before the last, hence -2, 
                                                         #time is 30 here, divide by 24 equal 1.25, convert to int then t is 1, add 1 then the result is 2
                e = int(float(line_items[-1]))
                if e == 1:# if event happens, then we know z the true time and we take a rendom number for 
                    z = t # 24
                    b = random.randint(z + 1, 2 * (z + 1)) # A random integer in range [start, end] including the end points. 
                                                            # randint(24 + 1, 2 * (24 + 1)) = randint(25, 50) = 39
                else: # if cens
                    b = t
                    z = random.randint(b + 1, 2 * (b + 1))
                # dummy y
                y = 0
                yzbx = ' '.join([str(y), str(z), str(b)] + x_items)
                yzbx_list.append(yzbx + '\n')

        with open(fnames_o[j], 'w') as f:
            f.writelines(yzbx_list)

      


# calculate features' statistical: max value, min value, mean value, and different value counts
def feat_stat(train, test):
    for feat in features:
        feat_dict[feat] = set() # we set a dictionary with the features names to add values to it in the for loops below
    #pdb.set_trace()
    # train
    with open(train, 'r') as f:
        lines = f.readlines()
        for line in lines:
            items = line.split(',')
            for i in range(len(items) - 2): # here -2 because we don't want to include the time and the label, which are located in the last two indexes
                feat_name = features[i]
                feat_dict[feat_name].add(float(items[i]))
    # test
    with open(test, 'r') as f:
        lines = f.readlines()
        for line in lines:
            items = line.split(',')
            for i in range(len(items) - 2):
                feat_name = features[i]
                feat_dict[feat_name].add(float(items[i]))
    
    # print result
    for feat in features:
        stats = feat_dict[feat]
        print("{} result:".format(feat))
        print("max value:{0}    min value:{1}   distinct cnt:{2}".format(max(stats), min(stats), len(stats)))

In [12]:
a,b = build_feat_index('C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\ndb_p\\1\\feat_ind.txt')

In [13]:
build_yzbx_data(a,train_file, test_file, 'C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\ndb_p\\1\\train_yzb.txt', 'C:\\Users\\raibe\\Desktop\\Thesis Code\\DRSA\\data\\ndb_p\\1\\test_yzb.txt')